project:
  type: website

website:
  title: "jsk"
  site-url: "https://www.jakobkottmann.com"
  description: "quantum computing, quantum chemistry and tequila"
  repo-url: https://github.com/kottmanj/blog
  repo-actions: [source, issue]
  navbar:
    logo: logo.png
    right:
      - about.qmd
      - tequila.qmd
      - icon: github
        href: https://github.com/kottmanj
      - icon: twitter
        href: https://twitter.com/jakobkottmann
      - icon: google
        href: https://scholar.google.com/citations?user=KVRv74kAAAAJ&hl=de&citsig=AMD79opNUyWS3nuk_2kmCYeqBBvmkRcQZQ
      - icon: mastodon
        href: https://qubit-social.xyz/@kottmann
      - icon: jsk.jpg
        href: https://www.researchgate.net/profile/Jakob-Kottmann
    favicon: logo.png
    open-graph: true 
format:
  html:
    theme:
      light: [flatly, theme-light.scss]
      dark: [darkly, theme-dark.scss]
    css: styles.css

execute:
  freeze: auto


