project:
  type: website

website:
  title: "jsk"
  site-url: "https://www.jakobkottmann.com"
  description: "quantum computing, quantum chemistry and tequila"
  image: preview.png
  repo-url: https://github.com/kottmanj/blog
  repo-actions: [source, issue]
  navbar:
    logo: logo.png
    right:
      - text: "blog"
        file: blog.qmd
      - tequila.qmd
      - text: "research"
        file: research.qmd
      - text: publications
        href: https://scholar.google.com/citations?user=KVRv74kAAAAJ&hl=de&citsig=AMD79opNUyWS3nuk_2kmCYeqBBvmkRcQZQ
      - text: "about"
        file: index.qmd
  favicon: favicon.ico
  twitter-card:
      site: "@jakobkottmann"
  open-graph: true
  google-analytics: G-V7DRP5E70N
  cookie-consent:
      type: express
      style: simple 

format:
  html:
    theme:
      light: [flatly, theme-light.scss]
      dark: [darkly, theme-dark.scss]
    css: styles.css

execute:
  freeze: auto


